### PR TITLE
Add Fetch ENS Address Example

### PR DESCRIPTION
**Pull request by Envoy-VC**
## Changes

Add a new example under `src/pages/examples/` which resolves ens names to address using `useEnsAddress` hook from wagmi

Contributing to Issue #4

Deployed Vercel address: https://nexth-3opluk9wv-envoy-vc.vercel.app/examples/fetch-ens

### CODE REVIEW

**Comment by Envoy-VC** [comment]
Hey @wslyvh can you please take a look at this example

**Comment by wslyvh** [comment]
Hi @Envoy-VC - this is great! Thank you so much for contributing

Sorry for the delay here.. Merged!

**Comment by wslyvh** [comment]
If you feel like it, it would be nice to make an example that works the other way as well.
Fetch an ENS name from an address. 

Could combine both on the same example page.

**Comment by Envoy-VC** [comment]
Thanks, will surely work on the other way.

**Pull request merged**
